#!/usr/bin/env bash
#
# Summary: Persist the preferred PhantomJS default version.
#
# Usage: phantomenv global <version>
#        phantomenv global --unset|-u

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$PHANTOMENV_DEBUG" ] && {
  set -x
}

# Set the version
version="$1"
version_file="${PHANTOMENV_ROOT}/version"

case "$version" in
  "")
    echo "phantomenv: a version or --unset is required" >&2
    exit 1
    ;;

  "-u" | "--unset")
    if [ -f "$version_file" ]; then
      rm "$version_file"
      echo "Unset $version_file"
    else
      echo "phantomenv: no global version to unset" >&2
      exit 1
    fi
    ;;

  *)
    echo "$version" > "$version_file"
    echo "Set $version_file to use $version"
    ;;
esac
