#!/usr/bin/env bash
#
# Summary: Persist the preferred PhantomJS version in the cwd.
#
# Usage: phantomenv local <version>
#        phantomenv local --unset|-u

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$PHANTOMENV_DEBUG" ] && {
  set -x
}

# Set the version
version="$1"

case "$version" in
  "")
    echo "phantomenv: a version or --unset is required" >&2
    exit 1
    ;;

  "-u" | "--unset")
    if [ -f "$(pwd)/.phantom-version" ]; then
      rm "$(pwd)/.phantom-version"
      echo "Unset local .phantom-version file"
    else
      echo "phantomenv: no local version to unset" >&2
      exit 1
    fi
    ;;

  *)
    echo "$version" > "$(pwd)/.phantom-version"
    echo "Created $(pwd)/.phantom-version with $version"
    ;;
esac
