#!/usr/bin/env bash
# Summary: Detect the file that sets the current phantomenv version

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$PHANTOMENV_DEBUG" ] && {
  set -x
}

find_local_version_file() {
  local root="$1"
  while [ -n "$root" ]; do
    if [ -e "${root}/.phantom-version" ]; then
      echo "${root}/.phantom-version"
      exit
    fi
    root="${root%/*}"
  done
}

find_local_version_file "$PHANTOMENV_DIR"
[ "$PHANTOMENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${PHANTOMENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
fi
