#!/usr/bin/env bash
# Summary: Display all versions of PhantomJS installed in `${PHANTOMENV_ROOT}/versions/*'.

# Bomb out if we hit an error, ever
set -e

# Verbose output in debug mode
[ -n "$PHANTOMENV_DEBUG" ] && {
  set -x
}

# Iterate over installed versions and write to output
for path in "${PHANTOMENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    echo "${path##*/}"
  fi
done
